In [1]:
import numpy as np
import pandas as pd
import math

In [18]:
poblacion = np.random.randint(0, 100, 100000)

muestra_aleatoria = np.random.choice(poblacion, 10000)

In [19]:
muestra_aleatoria = np.random.randint(1706, 1789, (5,8))
MIN = np.min(muestra_aleatoria)
MAX = np.max(muestra_aleatoria)
print(f"Valor Minimo: {MIN} y maximo {MAX}")
print('--------------------------------------')
print(muestra_aleatoria)

Valor Minimo: 1706 y maximo 1788
--------------------------------------
[[1754 1722 1746 1767 1729 1709 1774 1762]
 [1709 1749 1782 1740 1778 1707 1719 1773]
 [1788 1765 1783 1759 1725 1781 1765 1749]
 [1787 1727 1777 1778 1752 1736 1762 1734]
 [1715 1768 1706 1720 1746 1737 1777 1751]]


In [28]:
# Sort the data in ascending order
sorted_data = np.sort(muestra_aleatoria)

# Calculate the differences between consecutive values
differences = np.diff(sorted_data)

# Find the smallest non-zero difference
unit = np.min(differences[differences > 0])

print("Unidad de Variación de los datos:", unit)

Calculated Unit: 1


In [29]:
# Número de Intervalos de clase
int_clase = np.round(np.sqrt(muestra_aleatoria.size))
print(f"Número de Intervalos de clase: {int_clase}")
# Amplitud del Intervalo
amp_clase = np.around(((MAX-MIN)/int_clase), decimals=1)
amp_clase = math.modf(amp_clase)[1] + unit
print(f"Amplitud del Intervalo: {amp_clase}")

Número de Intervalos de clase: 6.0
Amplitud del Intervalo: 14.0


In [33]:
tabla_frecuencias = pd.DataFrame(columns=["L.I.", "L.S.", "Marca de Clase", "L.I. (Exacto)", "L.S. (Exacto)", "Frecuencia Absoluta"])

limites = np.arange(MIN, MAX + amp_clase, amp_clase) #sumamos la amplitud, solo para tener mas valores de los esperados
lim_inf = limites[:int(int_clase)]
lim_sup = limites[1:int(int_clase)+1]

tabla_frecuencias["L.I."] = lim_inf
tabla_frecuencias["L.S."] = lim_sup
tabla_frecuencias["Marca de Clase"] = (tabla_frecuencias["L.I."] + tabla_frecuencias["L.S."]) / 2
tabla_frecuencias["L.I. (Exacto)"] = (tabla_frecuencias["L.I."]-unit/2)
tabla_frecuencias["L.S. (Exacto)"] = (tabla_frecuencias["L.S."]+unit/2)
tabla_frecuencias["Frecuencia Absoluta"] = np.array([np.sum((muestra_aleatoria >= lim_inf[n]) & (muestra_aleatoria < lim_sup[n])) for n in range(lim_inf.size)]) #[LimInf - LimSup)

tabla_frecuencias

L.I.    L.S.  Marca de Clase  L.I. (Exacto)  L.S. (Exacto)  \
0  1706.0  1720.0          1713.0         1705.5         1720.5   
1  1720.0  1734.0          1727.0         1719.5         1734.5   
2  1734.0  1748.0          1741.0         1733.5         1748.5   
3  1748.0  1762.0          1755.0         1747.5         1762.5   
4  1762.0  1776.0          1769.0         1761.5         1776.5   
5  1776.0  1790.0          1783.0         1775.5         1790.5   

   Frecuencia Absoluta  
0                    6  
1                    5  
2                    6  
3                    6  
4                    8  
5                    9

In [34]:
np.sum(tabla_frecuencias["Frecuencia Absoluta"]) == muestra_aleatoria.size

True

In [35]:
tabla_frecuencias["Frecuencia Absoluta Relativa"] = tabla_frecuencias["Frecuencia Absoluta"] / muestra_aleatoria.size
np.sum(tabla_frecuencias["Frecuencia Absoluta Relativa"])

1.0000000000000002

In [36]:
tabla_frecuencias["Frecuencia Acumulada"] = np.array([np.sum(tabla_frecuencias["Frecuencia Absoluta"].iloc[:n].values) for n in range(1,int(int_clase)+1)])
tabla_frecuencias

L.I.    L.S.  Marca de Clase  L.I. (Exacto)  L.S. (Exacto)  \
0  1706.0  1720.0          1713.0         1705.5         1720.5   
1  1720.0  1734.0          1727.0         1719.5         1734.5   
2  1734.0  1748.0          1741.0         1733.5         1748.5   
3  1748.0  1762.0          1755.0         1747.5         1762.5   
4  1762.0  1776.0          1769.0         1761.5         1776.5   
5  1776.0  1790.0          1783.0         1775.5         1790.5   

   Frecuencia Absoluta  Frecuencia Absoluta Relativa  Frecuencia Acumulada  
0                    6                         0.150                     6  
1                    5                         0.125                    11  
2                    6                         0.150                    17  
3                    6                         0.150                    23  
4                    8                         0.200                    31  
5                    9                         0.225                    40

In [37]:
tabla_frecuencias["Frecuencia Acumulada Relativa"] = tabla_frecuencias["Frecuencia Acumulada"] / muestra_aleatoria.size
tabla_frecuencias

L.I.    L.S.  Marca de Clase  L.I. (Exacto)  L.S. (Exacto)  \
0  1706.0  1720.0          1713.0         1705.5         1720.5   
1  1720.0  1734.0          1727.0         1719.5         1734.5   
2  1734.0  1748.0          1741.0         1733.5         1748.5   
3  1748.0  1762.0          1755.0         1747.5         1762.5   
4  1762.0  1776.0          1769.0         1761.5         1776.5   
5  1776.0  1790.0          1783.0         1775.5         1790.5   

   Frecuencia Absoluta  Frecuencia Absoluta Relativa  Frecuencia Acumulada  \
0                    6                         0.150                     6   
1                    5                         0.125                    11   
2                    6                         0.150                    17   
3                    6                         0.150                    23   
4                    8                         0.200                    31   
5                    9                         0.225                    40   

   Frecuencia Acumulada Relativa  
0                          0.150  
1                          0.275  
2                          0.425  
3                          0.575  
4                          0.775  
5                          1.000